Gemfile, Gemfile.lock, app/controllers/search_controller.rb, app/javascript/components/ui/Search/SearchBar.jsx, app/models/question.rb, app/models/question/stimulus_case_study.rb, db/migrate/20250225130500_add_searchable_to_questions.rb, db/schema.rb, spec/models/question_spec.rb
646772b97279f50ff8b4cf83d292cd29c951f131
Following a thoughtbot article to add full text searching.
Ref:
- https://thoughtbot.com/blog/optimizing-full-text-search-with-postgres-tsvector-columns-and-triggers
4ad63c22e7ce86ac258dac9f757baa4fbf713639
In this commit, we need to have a new column on the questions table and
index it so we can set the backend up for full text search.
184f1ad898d1c0aa80550d9a003999db0d26e673
This commit will add logic to the Question model to make the pg_search
gem work.  We have the new `searchable` field which we are indexing the
`text` and `data` field words onto it.  We had to pay special
consideration for HTML strings and also specifically how it would work
with the StimulusCaseStudy question.  For that, we want to index all of
its child works' texts and …
=> I347 full text search

app/views/devise/sessions/new.html.erb
Updates the homepage text and link to Notch8 (the Notch8 url still redirects to the softserve site).
=> Update homepage to Notch8

db/seeds.rb
This commit will update the seeds file to use the actual subjects as prescribed by the config/subjects.yaml which uses the SubjectImporter to load.
=> 🧹 Update seeds to use SubjectImporter

app/services/subject_importer.rb, spec/fixtures/files/subjects_to_import.yaml, spec/services/subject_importer_spec.rb
Previously the subject importer would fail on a re-run, because the yaml was mixed case, and the records were created in all downcase. This resulted in `find_or_create` not finding the record, but the create failing due to a duplicate name. 
This patch fixes the subject importer and adds specs which verify it works.
=> Handle subject importer error & add specs

app/javascript/components/ui/Answers/StimulusCaseStudyAnswers.jsx, app/models/question.rb, app/models/question/stimulus_case_study.rb, spec/models/question/stimulus_case_study_spec.rb
This comit will fix the issue with stimulus case study sub-questions not being able to display their images.
Ref
- https://github.com/notch8/viva/issues/376
=> 🐛 fix Stimulus Case Study sub-questions' images

app/views/question/select_all_that_applies/_select_all_that_apply.xml.erb
author @sjproctor 
This commit fixes a bug in the Select All That Apply question type that was causing the answer correctness to be inverted. The `<not>` XML tag which indicates incorrect answers was being applied to correct answers.
Ref:
- https://github.com/notch8/viva/issues/339
=> 🐛 Fixes Canvas integration bug in Select All

app/models/concerns/matching_question_behavior.rb, spec/models/concerns/matching_question_behavior_spec.rb, spec/views/question/matchings/_matching.xml.erb_spec.rb
This is the results of a spike - 
Fix QTI export for Canvas matching questions to display all dropdown options
Related Issue:
- https://github.com/notch8/viva/issues/339
Previously, Canvas would only display a single option in dropdown menus for matching questions due to complex identifier strings. Changed identifier format to use simple numeric IDs (e.g. "100", "101") for choices and "response_1000" style IDs for responses.
Technical changes:
- Modified build_qti_data to generate simple numeric identifiers
- Added Set tracking to ensure uniqueness even with duplicate choice text
- Added tests to verify identifier uniqueness and formatting
- Added documentation explaining Canvas's undocumented identifier requirements
This change ensures all dropdown options are properly displayed in …
=> :bug: simplify ids for Matching allows us to upload into Canvas successfully

app/controllers/bookmarks_controller.rb, spec/controllers/bookmarks_controller_spec.rb
Ref:
- https://github.com/notch8/viva/issues/349
Exporting text and markdown files was getting all users bookmarks not just the current user
Only the current user's bookmarks should be available
=> 🐛 Bookmark exports scoped to current user

README.md, package.json, yarn.lock
- Exports were done through a filtered search and are now done via Bookmarking
- Supported question types in "Classic" Canvas have changed - adds a list of supported questions in Canvas
- Adds DocToc as a dev dependency to update the table of contents in the README
- Will require a dependency update (running yarn)
=> 📚 Update README to reflect export changes

app/controllers/bookmarks_controller.rb, spec/controllers/bookmarks_controller_spec.rb
Fixes the ability to download a user's bookmarks.
Adds a bit more to the specs verifying only the given user's bookmarks, and nothing that is not bookmarked.
The apparent cause of the bug was that the @questions loading was returning ids rather than full questions. 
Refs prior work: 
- https://github.com/notch8/viva/pull/389
- https://github.com/notch8/viva/pull/385
=> Fix Bookmark downloads

app/models/question.rb
This commit will remove the truncation from the final scrub of the text that goes into the searchable attribute.  We might want to see how this goes in production without a trucation and maybe put one in place if it affects performance.
Ref:
- https://github.com/notch8/viva/issues/394
=> 🐛 Remove trucation in the searchable attribute

app/models/question.rb
This commit will make it so that the .type_names method returns the types sorted alphabetically.
Ref:
- https://github.com/notch8/viva/issues/396
=> 🧹 Sort types

app/views/question/uploads/_upload.xml.erb, spec/views/question/uploads/_upload.xml.erb_spec.rb
Prior to this commit, Upload question types were being imported into canvas incorrectly, they were imported as essay questions.  This commit will change correct that.
Ref:
- https://github.com/notch8/viva/issues/401
=> 🐛 Fix Upload Question type for Canvas

app/models/image.rb, app/services/question_formatter/moodle_service.rb
This commit will refactor the base64 encode method to be on the Image model so other services can use it becuase we don't ever use the raw binary.
=> ♻️ Refactor base64 encode method

app/controllers/api/questions_controller.rb, app/javascript/components/ui/CreateQuestionForm/StimulusCaseStudy.jsx, app/javascript/components/ui/CreateQuestionForm/Upload.jsx, app/javascript/components/ui/CreateQuestionForm/index.jsx, app/javascript/constants/questionTypes.js, spec/controllers/api/questions_controller_spec.rb, spec/models/question/upload_spec.rb
Upload was not an option on the form or stimulus case study subquestion
- User can select Upload from the upload a question form
- User can select Upload as a subquestion when creating a Stimulus Case Study
<details>
<summary>Photo: Upload on the list of questions</summary>
</details>
<details>
<summary>Photo: Upload on the list of subquestions for Stimulus Case Study</summary>
</details>
<details>
<summary>Photo: Created Upload question and subquestion</summary>
</details>
=> 🎁 Adds Upload form and subquestion options

app/javascript/components/ui/Export/Export.css, app/javascript/components/ui/Export/ExportButton.jsx, app/javascript/components/ui/Export/ExportModal.jsx, app/models/question.rb, app/models/question/upload.rb
This design removes the hovering tool tip. Now users can immediately see what export types are available with each export button.
Issue
- https://github.com/notch8/viva/issues/428
=> 🧹[i428] - export buttons design follow up

app/services/bookmark_export_service.rb, app/services/question_formatter/base_service.rb, app/services/question_formatter/canvas_service.rb, app/services/question_formatter/d2l_service.rb, app/services/question_formatter/moodle_service.rb, app/services/zip_file_service.rb, spec/services/bookmark_export_service_spec.rb, spec/services/question_formatter/d2l_service_spec.rb, spec/services/zip_file_service_spec.rb
It's a two step process for D2L if we're including images.  The user must upload the images into their file system (we recommend /images/*). Then the user imports the CSV.  We've made the service output a zip file which has the CSV and images (if any).
Ref:
- https://github.com/notch8/viva/issues/414
=> 🎁 Make D2L export a zip with images (if any)

app/services/question_formatter/canvas_service.rb
This commit will add a step where we can make the XML a little prettier to look at.  Though this is very much a nice to have, it will serve us when we're trying to debug differences in XML for Canvas.
Before:
After:
=> 🎁 Add a step to pretty up the xml for canvas

app/models/image.rb, app/services/question_formatter/blackboard_service.rb, spec/services/question_formatter/blackboard_service_spec.rb
This commit will add logic to handle image exporting for Blackboard TSV text files.  We needed to base64 encode the binary of the image and add it into an <img> tag.
Ref:
- https://github.com/notch8/viva/issues/413
=> 🎁 Blackboard now exports images

app/services/question_formatter/blackboard_service.rb, spec/fixtures/files/bb_export.txt, spec/services/bookmark_export_service_spec.rb, spec/services/question_formatter/blackboard_service_spec.rb
99260887c68e87cf26dae49f7604592dc6e94319
This commit will account for the presence of return carriage characters
in the question.  If it has one then it will turn it into two <br/> tags
which will render correctly in Blackboard.
Ref:
- https://github.com/notch8/viva/issues/358
77627b4733c77de6eeb6af37df07b6f36bac428c
This commit cleans up a WARNING from rspec to pass in the type of error
to the raise_error matcher.
=> 🐛 Account for return carriage

cypress/e2e/auth.cy.jsx
Ref:
- https://github.com/notch8/viva/issues/409
There was no testing of the user auth workflow.
Testing to ensure the user can:
- log in
- sign up
- log out
- request a password reset
- reset their password
- use the "remember me" check box
- access authenticated routes if they are logged in
<details>
<summary>Photo: passing tests for the end-to-end auth workflow</summary>
</details>
The current functionality of the user auth workflow is predominantly happy path. Once these features exist in the application, the testing should be updated to include:
- logged out users attempting to access authenticated routes and being routed to the log in page (currently there is a Rails routing error)
- users attempting to sign in with invalid credentials should be given feedback on their attempt …
=> ✅ End-to-end test for user authentication

app/javascript/components/ui/CreateQuestionForm/Bowtie.jsx, app/javascript/components/ui/CreateQuestionForm/Categorization.jsx, app/javascript/components/ui/CreateQuestionForm/DragAndDrop.jsx, app/javascript/components/ui/CreateQuestionForm/Essay.jsx, app/javascript/components/ui/CreateQuestionForm/Matching.jsx, app/javascript/components/ui/CreateQuestionForm/MultipleChoice.jsx, app/javascript/components/ui/CreateQuestionForm/QuestionTypeDropdown.jsx, app/javascript/components/ui/CreateQuestionForm/SelectAllThatApply.jsx, app/javascript/components/ui/CreateQuestionForm/StimulusCaseStudy.jsx, app/javascript/components/ui/CreateQuestionForm/Upload.jsx, app/javascript/components/ui/CreateQuestionForm/index.jsx
Ref:
- https://github.com/notch8/viva/issues/335
On the Uploads page when a user selected a question type to create a single question via form, the dropdown menu button displayed the name of the selected question type. The name of the question type continued to be displayed on the button even after the question form was submitted.
This was the only label that determined which question form was being displayed.
The dropdown menu label stays the same regardless of user interaction. The dropdown menu displays only "Select Question Type"
Each question form has its own heading displaying the question type.
<details>
<summary>Photo: Dropdown menu displaying "Select Question Type" and the question type heading on the given form</summary>
</details>
This was an issue that was reported internally …
=> 🐛 Prevents label change on the Question dropdown

app/controllers/bookmarks_controller.rb, app/javascript/components/ui/Search/SearchFilters.jsx, config/routes.rb, spec/controllers/bookmarks_controller_spec.rb
This commit will revert a removal for the bookmark filtered search. Turns out this was indeed being used still.
=> 🐛 Adding the bookmark filtered back

app/javascript/components/ui/CreateQuestionForm/AnswerField.jsx, app/javascript/components/ui/CreateQuestionForm/AnswerSet.jsx
Ref:
- https://github.com/notch8/viva/issues/330
Console errors occurred when creating question types that used a radio button or checkbox.
This commit fixes the console errors that were appearing on the question form when the question type used checkboxes. The errors were due to an onClick action being used rather than the React-preferred onChange.
=> 🐛 Console errors on questions with checkboxes

app/javascript/components/ui/Export/Export.css, app/javascript/components/ui/Export/ExportButton.cy.jsx, app/javascript/components/ui/Export/ExportModal.cy.jsx, app/javascript/components/ui/Export/ExportModal.jsx, app/services/question_formatter/canvas_service.rb, spec/fixtures/files/imsmanifest.xml, spec/services/question_formatter/canvas_service_spec.rb
Ref:
- https://github.com/notch8/viva/issues/400
The Canvas export could only be imported to the Classic platform.
The Canvas export is uploadable to New and Classic Canvas.
<details>
<summary>Photo: Export modal</summary>
</details>
The New Canvas functionality was tested by Lisa at VIVA.
This zip was successfully uploaded to New Quiz by Lisa:
[questions-canvas-2025-03-18_19_45_08_185.zip](https://github.com/user-attachments/files/19328735/questions-canvas-2025-03-18_19_45_08_185.zip)
=> 🎁 Canvas exports to New and Classic platforms
